language: php
php:
  - 7.1
  - 7.2

before_script:
  - composer validate
  - composer install

script:
  - composer style-fix-download
  - composer style-fix
  - composer test
  - composer phpcov-merge

after_script:
  - vendor/bin/php-coveralls -v
